services:
  db:
    image: postgres:17-alpine
    volumes:
      - db:/var/lib/postgresql/blog/data/
    env_file:
      - .env
    restart: always
    container_name: drf-blog-db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - BlogNetwork

  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    container_name: drf-blog-container
    restart: always
    command: /start
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - '8001:8000'
    depends_on:
      - db
    networks:
      - BlogNetwork



  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'
    volumes:
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__Urls=http://*:80
      - ServerOptions__HostName=smtp4dev
    networks:
      - BlogNetwork




volumes:
  db:
  smtp4dev-data:

networks:
  BlogNetwork:
    driver: bridge
    name: BlogNetwork