# Generated by Django 5.2.5 on 2025-08-11 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('pb', 'pub'), ('drf', 'draft')], default='drf', max_length=3)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('slug', models.SlugField()),
                ('status', models.CharField(choices=[('pb', 'pub'), ('drf', 'draft')], default='drf', max_length=3)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='post_images')),
                ('snippet', models.CharField(blank=True, max_length=128)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(related_name='posts', to='blog.category')),
            ],
            options={
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['-published_date'], name='blog_post_publish_a3f863_idx')],
                'constraints': [models.UniqueConstraint(fields=('slug', 'published_date'), name='unique_slug_published_date')],
            },
        ),
    ]
