# Generated by Django 5.2.5 on 2025-08-21 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2025, 8, 21, 9, 50, 50, 380077, tzinfo=datetime.timezone.utc)),
        ),
    ]
