# Generated by Django 5.2.5 on 2025-08-21 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2025, 8, 21, 11, 8, 21, 79468, tzinfo=datetime.timezone.utc)),
        ),
    ]
