# Generated by Django 5.2.5 on 2025-08-30 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2025, 8, 30, 15, 22, 6, 800268, tzinfo=datetime.timezone.utc)),
        ),
    ]
