# Generated by Django 5.2.5 on 2025-09-01 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 1, 4, 53, 38, 567090, tzinfo=datetime.timezone.utc)),
        ),
    ]
