# Generated by Django 5.2.5 on 2025-09-02 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 2, 18, 42, 58, 655674, tzinfo=datetime.timezone.utc)),
        ),
    ]
