# Generated by Django 5.2.5 on 2025-09-10 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 10, 18, 0, 4, 121283, tzinfo=datetime.timezone.utc)),
        ),
    ]
