# Generated by Django 5.2.5 on 2025-09-12 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_alter_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 12, 11, 25, 38, 521744, tzinfo=datetime.timezone.utc)),
        ),
    ]
