# Generated by Django 5.2.5 on 2025-09-12 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_alter_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 12, 14, 15, 37, 826700, tzinfo=datetime.timezone.utc)),
        ),
    ]
